### ISSUE TITLE
Unable to use filesystem adapter.

### ISSUE THREAD

**Issue by DaveTheAve** [Ocramius/OcraCachedViewResolver#25]
### Issue ###
I am attempting to use the filesystem adapter so that I may benefit from a cached array yet still suffer from IO bottlenecks.

My intention is to use APC or memcache when available but fallback to the filesystem for the performance increase from no-caching at-all.

### Error Messages ###
```
E:\Development\FreelanceCollab\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php:1551
Error writing file 'E:\Development\FreelanceCollab\UwAmp\www\data\cache\zfcache-9b\zfcache-cached_template_map.dat'
```

```
E:\Development\FreelanceCollab\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php:1547
fwrite() expects parameter 2 to be string, array given
```

### My Config ###
```
<?php
/**
 * This configuration is for OcraCachedViewResolver - copy it to the `config/autoload`
 * directory of your ZF2 application and remove the `.dist` extension from its name.
 *
 * Don't forget to tweak it for your needs!
 */

use OcraCachedViewResolver\Module;

return [
    Module::CONFIG => [
        // configuration to be passed to `Zend\Cache\StorageFactory#factory()`
        // see http://framework.zend.com/manual/2.3/en/modules/zend.cache.storage.adapter.html#quick-start
        // Used to instantiate service `'OcraCachedViewResolver\\Cache\\ResolverCache'`
        'cache' => [
            'adapter' => [
                'name'    => 'filesystem',
                'options' => [
                    'cache_dir' => './data/cache',
                ],
            ],
        ],

        // following is the key used to store the template map in the cache adapter
        Module::CONFIG_CACHE_KEY     => 'cached_template_map',
        // name of a service implementing the `Zend\Cache\Storage\StorageInterface`, used to cache the template map
        Module::CONFIG_CACHE_SERVICE => 'OcraCachedViewResolver\\Cache\\ResolverCache',
    ],
];
```

**Comment by Ocramius** [comment]
Doesn't look like an issue with this module...

**Comment by DaveTheAve** [comment]
Any advice?

**Comment by DaveTheAve** [comment]
### Stack Traces ###
```
#0 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php(896): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('E:\\Development\\...', Array, true, 0)
#1 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\AbstractAdapter.php(689): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('cached_template...', Array)
#2 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php(771): Zend\Cache\Storage\Adapter\AbstractAdapter->setItem('cached_template...', Array)
#3 E:\UwAmp\www\vendor\ocramius\ocra-cached-view-resolver\src\OcraCachedViewResolver\View\Resolver\CachingMapResolver.php(105): Zend\Cache\Storage\Adapter\Filesystem->setItem('cached_template...', Array)
#4 E:\UwAmp\www\vendor\ocramius\ocra-cached-view-resolver\src\OcraCachedViewResolver\View\Resolver\CachingMapResolver.php(80): OcraCachedViewResolver\View\Resolver\CachingMapResolver->loadMap()
#5 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Resolver\AggregateResolver.php(101): OcraCachedViewResolver\View\Resolver\CachingMapResolver->resolve('application/ind...', Object(Zend\View\Renderer\PhpRenderer))
#6 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(203): Zend\View\Resolver\AggregateResolver->resolve('application/ind...', Object(Zend\View\Renderer\PhpRenderer))
#7 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(496): Zend\View\Renderer\PhpRenderer->resolver('application/ind...')
#8 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#9 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#10 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#11 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\View\Http\DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#13 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#14 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#15 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(352): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#16 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(327): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#17 E:\UwAmp\www\public\index.php(29): Zend\Mvc\Application->run()
#18 {main}
```
```
#0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fwrite() expect...', 'E:\\Development\\...', 1547, Array)
#1 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php(1547): fwrite(Resource id #454, Array)
#2 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php(896): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('E:\\Development\\...', Array, true, 0)
#3 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\AbstractAdapter.php(689): Zend\Cache\Storage\Adapter\Filesystem->internalSetItem('cached_template...', Array)
#4 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Cache\Storage\Adapter\Filesystem.php(771): Zend\Cache\Storage\Adapter\AbstractAdapter->setItem('cached_template...', Array)
#5 E:\UwAmp\www\vendor\ocramius\ocra-cached-view-resolver\src\OcraCachedViewResolver\View\Resolver\CachingMapResolver.php(105): Zend\Cache\Storage\Adapter\Filesystem->setItem('cached_template...', Array)
#6 E:\UwAmp\www\vendor\ocramius\ocra-cached-view-resolver\src\OcraCachedViewResolver\View\Resolver\CachingMapResolver.php(80): OcraCachedViewResolver\View\Resolver\CachingMapResolver->loadMap()
#7 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Resolver\AggregateResolver.php(101): OcraCachedViewResolver\View\Resolver\CachingMapResolver->resolve('application/ind...', Object(Zend\View\Renderer\PhpRenderer))
#8 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(203): Zend\View\Resolver\AggregateResolver->resolve('application/ind...', Object(Zend\View\Renderer\PhpRenderer))
#9 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(496): Zend\View\Renderer\PhpRenderer->resolver('application/ind...')
#10 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
#11 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(233): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#12 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\View\View.php(198): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#13 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\View\Http\DefaultRenderingStrategy.php(103): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#15 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#16 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('render', Object(Zend\Mvc\MvcEvent), Array)
#17 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(352): Zend\EventManager\EventManager->trigger('render', Object(Zend\Mvc\MvcEvent))
#18 E:\UwAmp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(327): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#19 E:\UwAmp\www\public\index.php(29): Zend\Mvc\Application->run()
#20 {main}
```

**Comment by Ocramius** [comment]
Yeah, simply looks like either mis-configuration or an issue inside the `Filesystem` storage adapter. Not an issue here, closing.

**Comment by DaveTheAve** [comment]
For anyone else interested my solution was to serialize and serialize the template map as such:

### CachingMapResolver.php ###
```
    /**
     * Load the template map into memory
     */
    private function loadMap()
    {
        $this->map = unserialize($this->cache->getItem($this->cacheKey));

        if (is_array($this->map)) {
            return;
        }

        $realResolverInstantiator = $this->realResolverInstantiator;
        $realResolver             = $realResolverInstantiator();

        if (! $realResolver instanceof ResolverInterface) {
            throw InvalidResolverInstantiatorException::fromInvalidResolver($realResolver);
        }

        $this->map = (new TemplateMapCompiler())->compileMap($realResolver);

        $this->cache->setItem($this->cacheKey, serialize($this->map));
    }
```

**Comment by Ocramius** [comment]
You should just add the serializer plugin to your cache, as described in [the documentation](http://framework.zend.com/manual/current/en/modules/zend.cache.storage.plugin.html#the-serializer-plugin)

**Comment by DaveTheAve** [comment]
Thank you Marco!

For everyone interested, here is what I did to get this working:

### Application\config\module.config.php ###
```
[...]
    'service_manager' => array(
        'factories' => array(
            'Zend\Cache\Storage\Adapter\Filesystem' => 'Application\Cache\Storage\Adapter\Factory\FilesystemFactory',
        ),
    ),
[...]
```

### config\autoload\ocra-cached-view-resolver.local.php.dist ###
```
[...]
        // name of a service implementing the `Zend\Cache\Storage\StorageInterface`, used to cache the template map
        Module::CONFIG_CACHE_SERVICE => 'Zend\Cache\Storage\Adapter\Filesystem',
[...]
```

### Application\Cache\Storage\Adapter\Factory\FilesystemFactory ###
```
[...]
<?php
namespace Application\Cache\Storage\Adapter\Factory;

use Zend\Cache\StorageFactory;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class FileSystemFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $cache = StorageFactory::factory(array(
            'adapter' => 'filesystem',
            'plugins' => array(
                'serializer'
            )
        ));

        $cache->setOptions(array(
            'cache_dir' => './data/cache'
        ));

        return $cache;
    }
}
[...]
```

I hope this helps!

**Comment by Ocramius** [comment]
Thanks for clarifying it! :-)

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by func0der** [comment]
For everyone who want to solve this quick and easy. change your config like this:

`<?php
/**
 * This configuration is for OcraCachedViewResolver - copy it to the `config/autoload`
 * directory of your ZF2 application and remove the `.dist` extension from its name.
 *
 * Don't forget to tweak it for your needs!
 */

use OcraCachedViewResolver\Module;

return [
    Module::CONFIG => [
        // configuration to be passed to `Zend\Cache\StorageFactory#factory()`
        // see http://framework.zend.com/manual/2.3/en/modules/zend.cache.storage.adapter.html#quick-start
        // Used to instantiate service `'OcraCachedViewResolver\\Cache\\ResolverCache'`
        'cache' => [
            'adapter' => [
                'name'    => 'filesystem',
                'options' => [
                    'cache_dir' => './data/cache',
                ],
            ],
            'plugins' => [ // <---- Add this part
                'serializer',
            ],
        ],

        // following is the key used to store the template map in the cache adapter
        Module::CONFIG_CACHE_KEY     => 'cached_template_map',
        // name of a service implementing the `Zend\Cache\Storage\StorageInterface`, used to cache the template map
        Module::CONFIG_CACHE_SERVICE => 'OcraCachedViewResolver\\Cache\\ResolverCache',
    ],
];`

Only thing changed is the `plugins`-Key.
Simple as that.
